/**
 * Elevation-based air density model using the International Standard Atmosphere (ISA).
 * Induced vertical break and horizontal break are both generated by the Magnus force,
 * which is proportional to air density. Gravitational drop is unaffected by altitude.
 *
 * ISA troposphere formula (valid 0–36,089 ft):
 *   ρ(h) / ρ(0) = (1 - 6.87559e-6 * h_ft)^5.2559
 */

export function airDensityRatio(altitudeFt) {
  const clamped = Math.max(0, Math.min(altitudeFt, 36000));
  return Math.pow(1 - 6.87559e-6 * clamped, 5.2559);
}

/**
 * Scale factor applied to Magnus-force-driven movement (iVB, HorzBreak)
 * when projecting from refAlt to targetAlt.
 */
export function movementScaleFactor(refAltFt, targetAltFt) {
  const refDensity = airDensityRatio(refAltFt);
  if (refDensity === 0) return 1;
  return airDensityRatio(targetAltFt) / refDensity;
}

/** Apply elevation correction to a single pitch's break values. */
export function adjustPitch(pitch, refAltFt, targetAltFt) {
  const scale = movementScaleFactor(refAltFt, targetAltFt);
  return {
    ...pitch,
    vertBreak: pitch.vertBreak !== null ? pitch.vertBreak * scale : null,
    horzBreak: pitch.horzBreak !== null ? pitch.horzBreak * scale : null,
    _elevAdjusted: true,
    _scale: scale,
  };
}

/** Percentage change in air density between two altitudes. */
export function densityChangePct(refAltFt, targetAltFt) {
  return (airDensityRatio(targetAltFt) / airDensityRatio(refAltFt) - 1) * 100;
}

/** Named MLB and college venue presets with approximate field elevations (ft). */
export const VENUE_PRESETS = [
  { name: 'Sea Level',        alt: 0 },
  { name: 'Boston (Fenway)',  alt: 20 },
  { name: 'New York',         alt: 55 },
  { name: 'Dallas',           alt: 430 },
  { name: 'Chicago',          alt: 595 },
  { name: 'Atlanta',          alt: 1050 },
  { name: 'Phoenix',          alt: 1082 },
  { name: 'Salt Lake City',   alt: 4226 },
  { name: 'Denver (Coors)',   alt: 5280 },
  { name: 'Colorado Springs', alt: 6035 },
];
